/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import javax.swing.*;

/**
 *
 * @author Daniel
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CBLugar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SpDia = new javax.swing.JSpinner();
        SpMes = new javax.swing.JSpinner();
        SpAno = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        RbtRedondo = new javax.swing.JRadioButton();
        RbtSencillo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        RbtAereo = new javax.swing.JRadioButton();
        RbtTerrestre = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        SpPasajero = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 160, -1));

        jLabel2.setText("Correo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        getContentPane().add(TxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 160, -1));

        jLabel3.setText("Lugar a viajar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        CBLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mazatlan", "Culiacan", "Mochis" }));
        getContentPane().add(CBLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jLabel5.setText("Dia");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel6.setText("Mes");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jLabel7.setText("Año");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        SpDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        getContentPane().add(SpDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 80, -1));

        SpMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(SpMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 80, -1));

        SpAno.setModel(new javax.swing.SpinnerNumberModel(2024, 2024, 2100, 1));
        getContentPane().add(SpAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 80, -1));

        jLabel8.setText("No de pasajero");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel9.setText("Tipo de viaje");

        RbtRedondo.setText("Redondo");
        RbtRedondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtRedondoActionPerformed(evt);
            }
        });

        RbtSencillo.setText("Sencillo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RbtRedondo)
                        .addGap(43, 43, 43)
                        .addComponent(RbtSencillo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel9)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtRedondo)
                    .addComponent(RbtSencillo))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 230, 70));

        RbtAereo.setText("Aereo");

        RbtTerrestre.setText("Terrestre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(RbtAereo)
                .addGap(18, 18, 18)
                .addComponent(RbtTerrestre)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtAereo)
                    .addComponent(RbtTerrestre))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 160, 40));

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        SpPasajero.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        getContentPane().add(SpPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbtRedondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtRedondoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtRedondoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Nombre=TxtNombre.getText();
        String Correo=TxtCorreo.getText();
        String Lugar=CBLugar.getSelectedItem().toString();
        String Dia=SpDia.getValue().toString();
        String Mes=SpMes.getValue().toString();
        String Ano=SpAno.getValue().toString();
        String Tipo=null;
        int Pasajero = (int) SpPasajero.getValue();
        int Precio=0;
        int PrecioTotal=0;
        
        if(RbtRedondo.isSelected() && RbtAereo.isSelected()){
            Tipo="Redondo/Aereo";
            if(Lugar=="Mazatlan")
                Precio=2950;
            if(Lugar=="Culiacan")
                Precio=2300;
            if(Lugar=="Mochis")
                Precio=2800;
        }else if(RbtRedondo.isSelected() && RbtTerrestre.isSelected()){
            Tipo="Redondo/Terrestre";
            if(Lugar=="Mazatlan")
                Precio=2500;
            if(Lugar=="Culiacan")
                Precio=2300;
            if(Lugar=="Mochis")
                Precio=2100;
        }else if(RbtSencillo.isSelected() && RbtAereo.isSelected()){
            Tipo="Sencillo/Aereo";
            if(Lugar=="Mazatlan")
                Precio=1450;
            if(Lugar=="Culiacan")
                Precio=1500;
            if(Lugar=="Mochis")
                Precio=1750;
        }else if(RbtSencillo.isSelected() && RbtTerrestre.isSelected()){
            Tipo="Sencillo/Terrestre";
            if(Lugar=="Mazatlan")
                Precio=640;
            if(Lugar=="Culiacan")
                Precio=750;
            if(Lugar=="Mochis")
                Precio=860;
        }
        
        PrecioTotal=Precio*Pasajero;
        
        JOptionPane.showMessageDialog(null, "Nombre: "+Nombre+"\n"
                +"Correo: "+Correo+"\n"
                +"Lugar de viaje: "+Lugar+"\n"+
                "Fecha del viaje: "+Dia+"/"+Mes+"/"+Ano+"\n"+
                "Numero de pasajeros: "+Pasajero+"\n"+
                "Tipo de viaje: "+Tipo+"\n"+
                "Precio unitario: "+Precio+"\n"+
                "Precio total: "+PrecioTotal);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBLugar;
    private javax.swing.JRadioButton RbtAereo;
    private javax.swing.JRadioButton RbtRedondo;
    private javax.swing.JRadioButton RbtSencillo;
    private javax.swing.JRadioButton RbtTerrestre;
    private javax.swing.JSpinner SpAno;
    private javax.swing.JSpinner SpDia;
    private javax.swing.JSpinner SpMes;
    private javax.swing.JSpinner SpPasajero;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
